### PR TITLE
WIP: App v2

### LINKED ISSUE #1: Support more labels with different statuses
When evaluating this app it seemed it can only handle one label when status is in one state. Would be great if this could handle more labels when status are in different states (for example first match will be used).

### LINKED ISSUE #2: Support optionally removing existing labels when setting
In our workflow, when an PR is waiting for the author, the PR is labeled with "waiting for code fix", or "waiting for author response". It would be nice if "Review Me"  when a new push comes in an all status are correct, the label is set, but also removes one or more labels. 

```yml
# Optional, removes all of these labels when setting 'label:'.
removeLabels:
  - waiting for code fix
  - waiting for author response
```

### LINKED ISSUE #3: Support "This branch has conflicts that must be resolved"
It would be nice if a PR has merge conflicts, that could be detected as a "context" as well. 

```
when:
  merge-conflicts: success
```

Though, would work if there was another app that detected this and added another status check that this app could be detected.

### LINKED ISSUE #4: Sets the review label on other event than a push event
It seems it gets a status event when there is a label change event. Is it possible to get it to only check statuses on a pull request push event? 
See https://github.com/PowerShell/DscResource.Tests/pull/271. I want to label the PR 'waiting for code fix' since it has merge conflicts. But the bot add back 'needs review' without a push event.

### PR DESCRIPTION
**Pull request by z0al**
- [x] Support removing labels ( fixes #2 and related to #4 )
- [ ] Merge conflicts aware ( fixes #3 )
- [x] Support multiple rules ( fixes #1)
- [x] Only check related PR ( fixes #4 )

This is a work in progress. Feel free to review, comment or discuss anything here. 

/cc @johlju

### CODE REVIEW

**Comment by z0al** [comment]
Correct me if I'm wrong, I think by adding support for removing labels it should resolve #4, right?

**Comment by johlju** [comment]
I will look at it and see. I’m not by a computer right now. If I can’t look at it this weekend, I will look at it on Monday! :)

**Comment by z0al** [comment]
Btw, I checked the "Merge conflicts aware #3 " section by mistake. I've not done something regarding that yet.

Well, I doesn't feel right to add "conflict" as status true/false just like other apps status. Do you have any thoughts regarding that?

**Comment by johlju** [comment]
@z0al Sorry been extremely busy so haven't had time to get back to this. :/ It still is on my list.

**Comment by z0al** [comment]
No worries :) 

I'm also busy these days but will complete the rest next weekend ISA

**Comment by z0al** [comment]
I'm back :)

**Comment by johlju** [comment]
> Correct me if I'm wrong, I think by adding support for removing labels it should resolve #4, right?

I don't think it will. See my new comment https://github.com/z0al/probot-review-me/issues/4#issuecomment-417237137.

> Well, I doesn't feel right to add "conflict" as status true/false just like other apps status. Do you have any thoughts regarding that?

Thoughts on this here: https://github.com/z0al/probot-review-me/issues/3#issuecomment-417238967

**Comment by johlju** [comment]
I think this so far only closes #2

**Pull request closed without merging**
